### ISSUE TITLE
F8 Error using bag item

### ISSUE THREAD

**Issue by Atthls** [renzuzu/renzu_bag#2]
Hey, I'm getting this error when using my **bag** item. Any idea? 

![image](https://user-images.githubusercontent.com/119019527/203878768-28fb66f2-23ee-4822-b2a3-f943ef6ef816.png)

I didn't change anything on the config.

**Comment by Gameadictive** [comment]
I have the same error without changing nothing.

**Comment by ajmedina** [comment]
Hi guys 
i test this script in ESX LEGACY last version and works perfectly! 
take updated all your dependencies like oxlib inventory oxmysql
Close That please

**Comment by renzuzu** [comment]
this was probably related from last version.
now its using ox_inventory exports item. this should prevent it

the cause is if es_extended is not set to use ox_inventory, metadata is nil.
